export class ReportFieldsConfigModel {
  configForm() {
    return [
      {
        property: 'marginRight',
        label: 'Margem da direita: ',
        type: 'number',
        minLength: 1,
        gridColumns: 3,
        gridSmColumns: 12,
        minValue: 0,
        errorMessage: 'Insira um valor maior ou igual a zero',
      },
      {
        property: 'marginTop',
        label: 'Margem superior: ',
        type: 'number',
        minLength: 1,
        gridColumns: 3,
        gridSmColumns: 12,
        minValue: 0,
        errorMessage: 'Insira um valor maior ou igual a zero',
      },
      {
        property: 'marginLeft',
        label: 'Margem da esquerda: ',
        type: 'number',
        minLength: 1,
        gridColumns: 3,
        gridSmColumns: 12,
        minValue: 0,
        errorMessage: 'Insira um valor maior ou igual a zero',
      },
      {
        property: 'marginBottom',
        label: 'Margem inferior: ',
        type: 'number',
        minLength: 1,
        gridColumns: 3,
        gridSmColumns: 12,
        minValue: 0,
        errorMessage: 'Insira um valor maior ou igual a zero',
      },
      {
        property: 'textFontSize',
        label: 'Fonte do texto: ',
        help: 'Tamanho da fonte para textos',
        type: 'number',
        minLength: 1,
        gridColumns: 3,
        gridSmColumns: 12,
        minValue: 1,
        errorMessage: 'Insira um valor maior que zero',
      },
      {
        property: 'titleFontSize',
        label: 'Fonte dos títulos: ',
        help: 'Tamanho da fonte para títulos',
        type: 'number',
        minLength: 1,
        gridColumns: 3,
        gridSmColumns: 12,
        minValue: 1,
        errorMessage: 'Insira um valor maior que zero',
      },
      {
        property: 'pageOrientation',
        label: 'Orientação da página',
        gridColumns: 8,
        gridSmColumns: 12,
        options: [
          { label: 'Horizontal', value: 'landscape' },
          { label: 'Vertical', value: 'portrait' },
        ],
      },
      {
        property: 'pageFormat',
        label: 'Formato da Página',
        gridColumns: 4,
        gridSmColumns: 12,
        options: [
          { label: 'A3', value: 'a3' },
          { label: 'A4', value: 'a4' },
          { label: 'A5', value: 'a5' },
        ],
      },
      {
        property: 'showHead',
        label: 'Exibit cabeçalho?',
        type: 'boolean',
        booleanTrue: 'Sim',
        booleanFalse: 'Não',
        gridColumns: 4,
        gridSmColumns: 12,
      },
      {
        property: 'showFooter',
        label: 'Exibit rodapé?',
        type: 'boolean',
        booleanTrue: 'Sim',
        booleanFalse: 'Não',
        gridColumns: 4,
        gridSmColumns: 12,
      },
      // {
      //  property: 'showNumbers',
      //  label: 'Exibir números das páginas?',
      //  type: 'boolean',
      //  booleanTrue: 'Sim',
      //  booleanFalse: 'Não',
      //  gridColumns: 4,
      //  gridSmColumns: 12,
      // },
      {
        property: 'waterMark',
        label: "Marca d'água",
        help: 'Texto que será aplicado em todas as páginas',
        gridColumns: 6,
        gridSmColumns: 12,
      },
      {
        property: 'password',
        help: 'A senha será solicitada ao abrir o arquivo',
        label: 'Senha para proteção do arquivo',
        secret: true,
        gridColumns: 6,
        gridSmColumns: 12,
      },
    ];
  }
}
